<a href="https://colab.research.google.com/github/jasimuddin365/Data-Preprocessing-and-Cleaning/blob/main/Text_Representation_%26_Vectorization_by_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## One Hot Encodings

In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Sample categorical data
data = np.array([['Red'], ['Green'], ['Blue'], ['Red'], ['Blue']])

# Initialize the OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)  # sparse_output=False returns an array

# Fit and transform the data
encoded_data = encoder.fit_transform(data)

In [2]:
encoded_data

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

### Bag of Words (BOW)

In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [6]:
bow = cv.fit_transform(df['text'])

In [7]:
bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>

In [8]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [9]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


### N-Grams

In [10]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [11]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [13]:
bow.toarray()

array([[0, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0, 1]])

In [14]:
#vocabulary
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [15]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
bow.toarray()

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0]])

In [18]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


### TF-IDF (Term frequency- Inverse document frequency)

In [19]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

,text,output
0,people watch dswithbappy,1
1,dswithbappy watch dswithbappy,1
2,people write comment,0
3,dswithbappy write comment,0


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [21]:
arr = tfid.fit_transform(df['text']).toarray()

In [22]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

### word2vec

data link: https://www.kaggle.com/datasets/khulasasndh/game-of-thrones-books

gdrive link: https://drive.google.com/file/d/1lbtAwzE7l0otXYFDtGUKKWzI83bD5D5H/view

In [23]:
import numpy as np
import pandas as pd
!pip install gensim
import gensim
import os

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 73.8 MB/s eta 0:00:00


In [24]:
!pip install --upgrade gensim --user

In [25]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [34]:
!unzip /content/GameOfThorone.zip

Archive:  /content/GameOfThorone.zip
  inflating: 001ssb.txt              
  inflating: 002ssb.txt              
  inflating: 003ssb.txt              
  inflating: 004ssb.txt              
  inflating: 005ssb.txt              


In [35]:
data = "/content/001ssb.txt"
data = "/content/002ssb.txt"
data = "/content/003ssb.txt"
data = "/content/004ssb.txt"
data = "/content/005ssb.txt"


In [36]:
import os
import re # Import regex for filtering filenames

story = []
# Iterate through files in the /content/ directory where the zip was unzipped
for filename in os.listdir('/content/'):
    # Only process files that match the pattern 'XXXssb.txt'
    if re.match(r'^\d{3}ssb\.txt$', filename):
        filepath = os.path.join('/content/', filename)
        # Use 'with' statement for proper file handling and 'cp1252' encoding
        with open(filepath, 'r', encoding='cp1252') as f:
            corpus = f.read()
            raw_sent = sent_tokenize(corpus)
            for sent in raw_sent:
                story.append(simple_preprocess(sent))

In [29]:
story

[]

In [30]:
len(story)

0

In [37]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [38]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [39]:
model.build_vocab(story)

In [40]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6570183, 8628190)

In [41]:
vec = model.wv.get_normed_vectors()

In [42]:
vec

array([[ 0.01605634, -0.08788791,  0.14757755, ..., -0.09185582,
         0.03510579,  0.12830856],
       [-0.06649071, -0.0681759 ,  0.03197698, ..., -0.0498754 ,
        -0.04991227,  0.06281967],
       [ 0.11578435, -0.04370132, -0.00627457, ...,  0.01174994,
         0.06355327, -0.0746162 ],
       ...,
       [ 0.11378195,  0.060469  , -0.02574107, ...,  0.0136939 ,
         0.11574978, -0.09724389],
       [ 0.1184008 ,  0.02357863,  0.07852772, ..., -0.18796381,
         0.19193862, -0.04826538],
       [ 0.20767277, -0.01729873, -0.03326204, ..., -0.01553321,
         0.02038955, -0.09134822]], dtype=float32)

In [43]:
len(vec[0])

100

In [44]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8207010626792908),
 ('targaryen', 0.779039740562439),
 ('queen', 0.7509008049964905),
 ('unburnt', 0.7369711995124817),
 ('princess', 0.7340788841247559),
 ('elia', 0.717321515083313),
 ('myrcella', 0.7047684788703918),
 ('viserys', 0.6992987394332886),
 ('margaery', 0.6879338622093201),
 ('khal', 0.6722734570503235)]

In [45]:
model.wv.similarity('arya','sansa')

np.float32(0.858255)

In [46]:

y = model.wv.index_to_key

In [47]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'know',
 'see',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'face',
 'still',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [48]:
from sklearn.decomposition import PCA

In [49]:
pca = PCA(n_components=3)

In [57]:
x = pca.fit_transform(model.wv.get_normed_vectors())

In [58]:
x

array([[ 0.16135828,  0.59766394, -0.02536647],
       [ 0.14767317,  0.31494057,  0.05714937],
       [-0.2847218 ,  0.5614679 ,  0.22057869],
       ...,
       [-0.18441422,  0.026057  ,  0.33148235],
       [ 0.10811062,  0.08876035, -0.04985587],
       [-0.43857372,  0.23173562,  0.36104685]], dtype=float32)

In [65]:
len(x[0])

3

In [68]:
import plotly.express as px
fig = px.scatter_3d(x[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()